### ISSUE TITLE
UI Enhancement: Show progress bar if picture is generating

### ISSUE THREAD

**Issue by haseeb-xd** [haseeb-xd/image-verse#5]
>Currently no progress bar is shown to user.

https://github.com/haseeb-xd/image-verse/assets/47222685/94875b53-5f15-4c8c-ba31-c3559039732b

**Comment by PC-11-00** [comment]
Can I work on it.

**Comment by haseeb-xd** [comment]
> Can I work on it.

yes, assigning.

**Comment by PC-11-00** [comment]
https://github.com/haseeb-xd/image-verse/assets/76156941/da128754-104d-41aa-a9d5-4dfb8cb392e6

Will this work?

**Comment by haseeb-xd** [comment]
> Screen.Recording.2023-10-20.at.10.19.55.PM.mov 
> Will this work?

Can you make it same yellow color? Other than that looks good.

**Comment by PC-11-00** [comment]
https://github.com/haseeb-xd/image-verse/assets/76156941/c0e84424-a777-499e-a18f-864c737bfdcb

Done

**Comment by PC-11-00** [comment]
https://github.com/haseeb-xd/image-verse/assets/76156941/c9b905c2-f557-447a-95e3-67f876c6c255

Done

**Comment by PC-11-00** [comment]
Made a PR please have a look at it.
